### ISSUE TITLE
Flask 1.1 breakage

### ISSUE THREAD

**Issue by guruofgentoo** [level12/keg#126]
Tests are not passing with Flask 1.1, specifically from TestCLI2. Probably related to #90, but I wanted to document this limit. #125 adjusts the requirements to limit flask version.

**Comment by nZac** [comment]
I dug into this a fair bit more because I wanted a 1.1 feature.  These are the tests that fail: 
https://github.com/level12/keg/blob/dba2cf40fbae4d202f839dc2a5bca3d32e57f828/keg/tests/test_cli.py#L40-L89

It doesn't seem to be related directly to #90, as applying that patch doesn't fix the issue but there is something wonky happening with the `import_name` with https://github.com/level12/keg/blob/dba2cf40fbae4d202f839dc2a5bca3d32e57f828/keg_apps/cli2/app.py#L6-L11

Everything breaks because of this tests: https://github.com/level12/keg/blob/dba2cf40fbae4d202f839dc2a5bca3d32e57f828/keg/tests/test_app.py#L8-L14 but I can't seem to figure out why. This doesn't seem to do anything special but removing it fixes the other breaking tests.

I ran a `git bisect` and discovered that this is the first failing commit: https://github.com/pallets/flask/commit/ec1ccd753084c6ff3215b9a64ba46d6af56715bd. I think because they changed the where the [CLI gets setup](https://github.com/pallets/flask/commit/ec1ccd753084c6ff3215b9a64ba46d6af56715bd#diff-ee0f9ead1ef8dfffdc273d4357401539R945-R952) and how it changes in the [`Flask.__init__`](https://github.com/pallets/flask/commit/ec1ccd753084c6ff3215b9a64ba46d6af56715bd#diff-c3c1b62367ae818e58e148e2e1840b39L603-R605) we are having some weird interaction when an error occurs from the first test. I wasn't able to figure out where that would be.

I wonder if it would be good to take a look at the CLI setup and restructure that from a first-principles view.
