### ISSUE TITLE
rule() when used w/ a relative URL should not result in the default URL also being available

### ISSUE THREAD

**Issue by rsyring** [level12/keg#179]
```python

class ApprovalReview(ApprovalBaseView):
    rule('<int:week_id>', post=True)

    def get(self, week_id):
        pass

```

```
$ marshal develop routes | grep review
admin.approval-review                         GET,OPTIONS,HEAD,POST   /admin/approval-review
admin.approval-review                         GET,OPTIONS,HEAD,POST   /admin/approval-review/<int:week_id>
```

I was expecting only the second route in the list above to be generated.  I think the first route being present is a bug.

**Comment by guruofgentoo** [comment]
Looks like this was actually by design. See the [test HelloWorld view](https://github.com/level12/keg/blob/a528fe2c6381fd4d845060218a134c57d0ad71b9/keg_apps/web/views/routing.py#L61):
- it gets a default route because no absolute route rule is given
- it needs that default route, because a real case of args is to use the default kwarg on `get`
- but it also needs the relative rule, to supply different name values

So when the [blueprint init](https://github.com/level12/keg/blob/a528fe2c6381fd4d845060218a134c57d0ad71b9/keg/web.py#L318) happens, the default route is generated because there was no absolute.

In contrast, the [HelloReq](https://github.com/level12/keg/blob/a528fe2c6381fd4d845060218a134c57d0ad71b9/keg_apps/web/views/routing.py#L92) test example provides an absolute route, for the purpose of disabling default route behavior.

IMO this should have been done differently, because explicit is better than implicit. I.e. the default route should not be generated unless there aren't any rules at all. I don't think there's a good way to detect whether the given rules cover enough args that a default route is not necessary. Once explicit rules are in the picture, it seems like the "magic" should just stop, and the developer should provide a default route rule if one is needed.

We'll need to think on this a little bit and decide what the best path forward is. We could put in a warning for whenever the default route is generated but rules are present. But that would warn on a lot of views, where the intended target case that would be a breaking change may be relatively rare. And, there would not be a great way to "fix" the source of the warning in an app.

I'd really opt for just breaking it, documenting that, and having a note in the changelog as well. I'll be changing the minor version number for dropping python 2 support anyway, so it's as good a time as any to make this kind of change.
