### ISSUE TITLE
Customizing the DB Manager is harder than it could be

### ISSUE THREAD

**Issue by rsyring** [level12/keg#59]
I init `keg.db.db` in `keg.db` which means it's really hard to customize `KegSQLAlchemy/SQLAlchemy` classes by subclassing and overriding.  This proved especially true when trying to setup custom json serialization methods for a customer project.

I believe `keg.db.db` would be better served being a local proxy like `flask.request` and redirecting that to the real instance on the app.  Then the app would need to have a setup method for that class.

**Comment by nZac** [comment]
I don't think this is going to be possible without a _lot_ of effort. If we make `keg.db.db` a `LocalProxy` object to `flask.current_app.db` it will require an `app.app_context` to exist.  But `db.Model` needs to exist at import time so that we can declare entities with `MyEntity(db.Model)`.

Now, you could move the `declarative_base` out of FSA and set that up manually. The code that it runs at `__init__` time is [here](https://github.com/pallets/flask-sqlalchemy/blob/master/flask_sqlalchemy/__init__.py#L774-L805) and has some special stuff like setting up the query class.

My concern is that, `SQLAlchemy` is expected to be a global, like all flask extensions, and we will keep running into more and more of these issues. For example, the Query class which is automatically put onto `db.Model` is passed in at `__init__` time, so is the `metadata`.

**Comment by guruofgentoo** [comment]
The issues Nick pointed out here are still valid. Without completely wrapping the flask-sqlalchemy layer, this would be problematic at best.

I think most of the cases that would require this sort of modification are covered now, through:
- the KEG_DB_ENGINE_OPTIONS config setting
- the newer db_before_import signal
  - This calls connected methods prior to running visit_modules to gather entities.
  - Anything that needs to be sorted out at import time for entities can be placed here. That is, as long as the developer is careful not to import modules with entities prior to the hook, which is noted in the signals docs.

Any other solution will also require the app to be partially loaded before the fully-configured entity may be used, so this seems sufficient for now.
